steps:
- name: 'postgres'
  env: 'POSTGRES_PASSWORD=mysecretpassword'
  args: ['bash', 'script1.sh']
  id: A
  waitFor: ['-']
- name: ' jbergknoff/postgresql-client'
  args: ['-u', 'script2.sh']
  env: 'POSTGRES_PASSWORD=mysecretpassword'
  id: B
  waitFor: ['-']
