secrets:
- kmsKeyName: projects/standf-188123/locations/global/keyRings/standf/cryptoKeys/source_clear
  secretEnv:
    SRCCLR_API_TOKEN: CiQAdEvmb89Pd6q6p30J73YDB9T74o4YoFSNOTGOFVaX9BWecwoSyQMA7PAGf9VVxEWAGuNvULE0h1hMCz7gKqrz8zVZWEeXaDgsk4LAIxBmgSy1I+wBoFNbXsfrhNF8Q8fkmxiRi2oIti3luy1Toutd4QA5QFsfsFfyYCW/tGV2ES5o76atWXfjcpwP5yG3sElmRHxS+tPzb2iXdE4maMpdFeme5HFq0GUh6Aj4z01C+epXxMqNFMfRxaDCrvj86shKOXjrdCzbojG5JcrYj4fq1CAl6dHcP0CtDU7AHx0icP7WNiiQ8LCsOYL0KXK9fRAK4uSgoNG7zfAI/V9YTRQpBOYgse1TgAX2iX+e/o1nKsF358zbqEgdo4B3q1yOMOU7+/m/mk5bQ7Q7ICPtzWO/8OymZmzNs7ZhSig3CldjlEJRlzlOb1k8/LIqgV3c4zOXe4XWNNyo8uH1EZijkQlTW1kU7RUKidh5cJEJ5Ret+bmd12XN6kG20K64a9q1UNeZMqhNMA1hfoldu437byG9Pb36YoJbBzUoQ8PUZr1j87zqd/3tdo3ufpRo6SzDEvQag38HTlkzzHU8qHBppxXi6lRQFZrDCqZrTna+tREK5oFjMIWTYiWZ9ghIz5qGLa5PP/SglZDttyPpWXs0Cfil

steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot:rmk', '.']
- name: 'gcr.io/standf-188123/github-memanikantan-source_clear_mvn:9f64a57eaf51785cc9371764e5bc80a067bce867'
  secretEnv: ['SRCCLR_API_TOKEN']


images: ['gcr.io/$PROJECT_ID/spring-boot']
tags:
- "test"
- "tag2"