steps:
#- name: 'sriman-biarca/postgres-1'
- name: 'postgres'
  env: ['POSTGRES_PASSWORD=test1234']
  entrypoint: 'bash'
  args: ['bash', 'workspace/postgres.sh']
  id: A
  waitFor: ['-']
- name: 'jbergknoff/postgresql-client'
  entrypoint: 'bash'
  args: ['bash', 'client.sh']
  id: B
  waitFor: ['A']
