steps:
- name: 'postgres'
  env: 'POSTGRES_PASSWORD=test1234'
  args: ['bash', 'script1.sh']
  id: A
  waitFor: ['-']
- name: 'jbergknoff/postgresql-client'
  args: ['bash', 'script2.sh']
  id: B
  waitFor: ['-']
