steps:
- name: 'sriman-biarca/postgres-1'
  env: ['POSTGRES_PASSWORD=test1234']
  args: ['bash', 'postgres.sh']
  id: A
  waitFor: ['-']
- name: 'jbergknoff/postgresql-client'
  args: ['bash', 'client.sh']
  id: B
  waitFor: ['-']
